### ISSUE TITLE
> Task :react-native-create-thumbnail:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by VitoFromEarth** [souvik-ghosh/react-native-create-thumbnail#87] opened 2023-02-06 11:14 UTC
**Describe the bug**
On building react native application with version 0.71 i have this issue
```
node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:192:
error: unreported exception IOException; must be caught or declared to be thrown
        retriever.release(); 
```

**To Reproduce**
1. Just try to build debug version

**Version**
`react-native-create-thumbnail` 1.6.4

**Expected Results**
Build without issues

There is nothing specific regarding graddle stuff. Tried with clean project

**Comment by VitoFromEarth** [comment] 2023-02-07 16:50
> same issue, any solution?

For test I have wrapped `CreateThumbnailModule.java:192` with try catch and I could continue building the app. So
I suppose that author of the package should do the same and issue will be gone

**Comment by peyman-hakemi** [comment] 2023-02-07 16:58
i replaced 

with
` retriever.release();`
` try {
  retriever.release();
} catch (IOException ex) {
  // handle the exception here
}`

this worked to

**Comment by souvik-ghosh** [comment] 2023-02-07 17:18
Duplicate of https://github.com/souvik-ghosh/react-native-create-thumbnail/issues/76

**Closed** 2023-02-18 19:09 UTC
Labels: bug

**Comment by miguelangarano** [comment] 2023-03-24 15:44
> i replaced ` retriever.release();` with
> 
> ` try { retriever.release(); } catch (IOException ex) { // handle the exception here }`
> 
> this worked to

This works for me

**Comment by SibelcoMX** [comment] 2023-08-25 16:30
Any idea when a new version will be available on npm?

**Comment by arminghm** [comment] 2023-09-01 08:56
@SibelcoMX you can use version [v2.0.0-rc.2](https://github.com/souvik-ghosh/react-native-create-thumbnail/releases/tag/v2.0.0-rc.2) using npm, bear in mind that it is a pre-release version

using `npm`
`npm i react-native-create-thumbnail@2.0.0-rc.2`

or

`yarn add react-native-create-thumbnail@2.0.0-rc.2`
