### ISSUE TITLE
I have granted read and write permissions, i can see my path, but how can i access the path using for example videoPlayer thumbnail parameter.

### ISSUE THREAD

**Issue by aleluiah** [souvik-ghosh/react-native-create-thumbnail#20] opened 2020-07-01 21:23 UTC
below is my code for example:

<VideoPlayer resizeMode='stretch' thumbnail={{uri: 'file:///data/user/0/com/myfirstproject/cache/thumbnails/thumb-6d12fb87-4200-4a52-85ab-d9a0efa3720f.jpeg'}} repeat={false} playWhenInactive={false} video={{uri: urii}} style={{ maxWidth: '100%', height: 250, padding: 0, margin: 0 }} mediaPlaybackRequiresUserAction = {true} />

**Comment by souvik-ghosh** [comment] 2020-07-31 19:14
closing as duplicate of https://github.com/souvik-ghosh/react-native-create-thumbnail/issues/21

**Closed by souvik-ghosh** 2020-07-31 19:14 UTC
Labels: duplicate
