### ISSUE TITLE
Hotfix CreateThumbnailModule.java:192

### ISSUE THREAD

**Issue by yevheniishabelnyk** [souvik-ghosh/react-native-create-thumbnail#85] opened 2023-01-23 09:21 UTC
Hello! 
When I try to deploy the app, I am getting the bug with:
```
> Task :react-native-create-thumbnail:compileReleaseJavaWithJavac FAILED
/Users/runner/work/1/s/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:192: error: unreported exception IOException; must be caught or declared to be thrown
        retriever.release();
```

I found the solution, we should to change line 192 with:
```
try {
  retriever.release();
} catch (IOException ex) {
  // handle the exception here
}
```

Could you do it ASAP, please, cause I can't deploy my app.

Thank you!

**Comment by souvik-ghosh** [comment] 2023-01-23 09:34
@yevheniishabelnyk, Duplicate of https://github.com/souvik-ghosh/react-native-create-thumbnail/issues/76

**Closed by souvik-ghosh** 2023-01-23 09:34 UTC
Labels: bug
