### ISSUE TITLE
Build error in ANDROID SDK 33

### ISSUE THREAD

**Issue by hdh0319** [souvik-ghosh/react-native-create-thumbnail#98] opened 2023-08-29 08:00 UTC
This pakcage support Android sdk 33? An error occurs during build.

**Comment by AlekoG** [comment] 2023-08-30 06:53
Same thing: 
`Task :react-native-create-thumbnail:compileDebugJavaWithJavac FAILED`

After upgrading to 33 its not building.

**Comment by joaohedy** [comment] 2023-08-31 09:41
Same issue. 
I managed to return to 31 and it worked fine. But other libraries require 33.

So If no solution is available, I need to find another library that works. :-(

**Comment by bryancisler** [comment] 2023-08-31 21:59
Fork and clone the project. Go to the android/src/main/java/com/createthumbnail/CreateThumbnailModule.hava file. 

Go to line 191 and replace the code

  ```
     Bitmap image = retriever.getFrameAtTime(time * 1000, MediaMetadataRetriever.OPTION_CLOSEST_SYNC);
        retriever.release();
        if (image == null) {
            throw new IllegalStateException("File doesn't exist or not supported");
        }
        return image; 
```
to this
```
 Bitmap image = retriever.getFrameAtTime(time * 1000, MediaMetadataRetriever.OPTION_CLOSEST_SYNC);
try {
    retriever.release();
} catch (Exception e) { // Catching Exception class as it's unclear what specific exception you're facing
    // Handle or log the exception here
    e.printStackTrace();
}

if (image == null) {
    throw new IllegalStateException("File doesn't exist or not supported");
}
return image;
```

**Comment by padulamathias** [comment] 2023-09-04 12:19
Hello,

From Aug 31 API 33 is the minimum supported for sending updates to the Play Store.

I am having the same issue using the last version of react-native-create-thumbnail.

React Native: 0.71.6

**Comment by humanzai** [comment] 2023-09-06 13:27
Opened a PR #99 with a fix

**Comment by xgenem** [comment] 2023-11-20 18:23
Using the version `2.0.0-rc.2`. Problem still persists.

**Comment by souvik-ghosh** [comment] 2023-12-29 23:15
duplicate of https://github.com/souvik-ghosh/react-native-create-thumbnail/issues/76. fixed in the latest version

**Closed by souvik-ghosh** 2023-12-29 23:15 UTC
Labels: bug
