### ISSUE TITLE
Unreported exception error IOException; it must be caught or declared to be thrown. "retriever.release()"

### ISSUE THREAD

**Issue by DiaoMIngHero** [souvik-ghosh/react-native-create-thumbnail#96] opened 2023-06-28 02:40 UTC
**Describe the bug**
![image](https://github.com/souvik-ghosh/react-native-create-thumbnail/assets/48375019/09f02e93-b33f-4884-9375-498b67be81a6)

**To Reproduce**
1.add dependency
2.run

**Version**
`react-native-create-thumbnail` 1.6.4

**Expected Results**
no exception

**Snack, code example, screenshot, or link to a repository**

**Comment by yoon123456** [comment] 2023-07-03 06:47
I have the same problem.
please solve

**Comment by MichaelDanielTom** [comment] 2023-07-03 16:09
The easiest way to fix until prs are approved is to use [patch-package](https://github.com/ds300/patch-package) to add those two errors in java like:

```
diff --git a/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java b/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java
index 9bd67d8..6188e43 100644
--- a/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java
+++ b/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java
@@ -168,7 +168,7 @@ public class CreateThumbnailModule extends ReactContextBaseJavaModule {
         return dir;
     }
 
-    private static Bitmap getBitmapAtTime(Context context, String filePath, int time, Map headers) {
+    private static Bitmap getBitmapAtTime(Context context, String filePath, int time, Map headers) throws IOException, IllegalStateException {
         MediaMetadataRetriever retriever = new MediaMetadataRetriever();
         if (URLUtil.isFileUrl(filePath)) {
             String decodedPath;

```

**Comment by Shiva207892** [comment] 2023-07-05 11:59
try {
    // Code that may throw an IOException
    retriever.release();
} catch (IOException e) {
    // Handle the IOException, you can log it or take appropriate actions.
    e.printStackTrace();
}

**Comment by mattlewer** [comment] 2023-07-07 09:07
Same problem here, preventing us running a new build.

**Comment by saif-o99** [comment] 2023-07-11 09:22
@souvik-ghosh Same here with:

"react-native": "0.71.7"
"react-native-create-thumbnail": "1.6.4"

**Comment by MarcoBallotti** [comment] 2023-08-28 12:47
> try { // Code that may throw an IOException retriever.release(); } catch (IOException e) { // Handle the IOException, you can log it or take appropriate actions. e.printStackTrace(); }

this solved for me

**Comment by souvik-ghosh** [comment] 2023-12-29 23:14
Duplicate of https://github.com/souvik-ghosh/react-native-create-thumbnail/issues/76

**Closed by souvik-ghosh** 2023-12-29 23:14 UTC
Labels: duplicate
